cuenta/urls.py
from django.urls import path
from .views import profile, actualizar_perfil

urlpatterns = [
    path('profile/', profile, name='profile'),
    path('update/', actualizar_perfil, name='update-profile')
]

empleado/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('registration', views.registro_gerente, name='empleado-registration'),
    path('list', views.lista_gerente, name='empleado-list'),
    path('cargar_locacion', views.cargar_locacion, name='cargar_locacion'),
]

sistemaERP/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_page
from . import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    path('', include('administracion.urls')),
    path('gerente/', include('gerente.urls')),
    path('consultor/', include('consultor.urls')),
    path('procesos/', include('procesos.urls')),
    path('empleado/', include('empleado.urls')),
    path('resultado/', include('resultado.urls')),
    path('domicilio/', include('domicilio.urls')),
    path('cuenta/', include('cuenta.urls')),
    path('asistencia/', include('asistencia.urls')),
    # path('advanced_filters/', include('advanced_filters.urls'))
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/models.py
from django.db import models
from domicilio.models import Zona,Locacion,Anexo
from administracion.models import Designacion
from procesos.models import Departmento

# Create your models here.
class EmpleadoDireccionInfo(models.Model):
    zona = models.ForeignKey(Zona, on_delete=models.CASCADE, null=True)
    locacion = models.ForeignKey(Locacion, on_delete=models.CASCADE, null=True)
    anexo = models.ForeignKey(Anexo, on_delete=models.CASCADE, null=True)
    cp = models.TextField()

    def __str__(self):
        return self.cp

class EducacionInfo(models.Model):
    nombre_de_evaluacion = models.CharField(max_length=100)
    instituto = models.CharField(max_length=255)
    grupo = models.CharField(max_length=100)
    grado = models.CharField(max_length=45)
    reunion = models.CharField(max_length=45)
    anio_presente = models.IntegerField()

    def __str__(self):
        return self.nombre_de_evaluacion

class EntrenamientoInfo(models.Model):
    nombre_entrenamiento = models.CharField(max_length=100)
    anio = models.IntegerField()
    duracion = models.IntegerField()
    lugar = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre_entrenamiento

class EmpleadoTrabajoInfo(models.Model):
    eleccion_de_categoria = (
        ('bcs', 'BCS'),
        ('nacionalizado', 'nacionalizado'),
        ('cuota del 10%', 'cuota del 10%'),
        ('no gubernamental', 'no gubernamental')
    )
    categoria = models.CharField('Categoría',choices=eleccion_de_categoria, max_length=45)
    dia_de_ingreso = models.DateField('Día de ingreso')
    nombre_instituto = models.CharField('Nombre de Instituto',max_length=100)
    designacion_de_trabajo = models.ForeignKey(Designacion, on_delete=models.CASCADE)
    departmento = models.ForeignKey(Departmento, on_delete=models.CASCADE)
    escala = models.IntegerField('Escala')
    grado_publicacion = models.CharField('Grado de publicación',max_length=45)
    primer_periodo_de_contrato = models.IntegerField('Primer periodo de tiempo vencimiento de contrato')
    segundo_periodo_de_contrato = models.IntegerField('Segundo periodo de tiempo vencimiento de contrato')
    promocion_de_vencimiento = models.IntegerField('Promocion de vencimiento año/contrato')
    renovacion_contrato = models.IntegerField('Licencia de renovación por año/contrato')
    tiempo_jubilacion = models.IntegerField('Año jubilación esperado')


    def __str__(self):
        return self.nombre_instituto

class ExperienciaInfo(models.Model):
    nombre_instituto = models.CharField('Nombre del Instituto *',max_length=100)
    designation = models.CharField('Designación',max_length=45)
    entrenador = models.CharField('Capacitador',max_length=45)


    def __str__(self):
        return self.nombre_instituto

class PersonalInfo(models.Model):
    nombre = models.CharField('Nombre',max_length=45)
    foto = models.ImageField('Foto')
    fecha_nac = models.DateField('Fecha de nacimiento')
    lugar_nac = models.CharField('Lugar de nacimiento',max_length=45)
    eleccion_nacionalidad = (
        ('México', 'México'),
        ('Alemania', 'Alemania'),
        ('Rusia', 'Rusia'),
        ('Usa', 'Usa'),
        ('Otros', 'Otros')
    )
    nacionalidad = models.CharField('Nacionalidad',max_length=45, choices=eleccion_nacionalidad)
    eleccion_religion = (
        ('Islam', 'Islam'),
        ('Hinduismo', 'Hinduismo'),
        ('budismo', 'budismo'),
        ('cristianismo', 'cristianismo'),
        ('Otros', 'Otros')
    )
    religion = models.CharField('Religión',max_length=45, choices=eleccion_religion)
    eleccion_de_genero = (
        ('masculino', 'Masculino'),
        ('femenino', 'Femenino'),
        ('otro', 'Otro')
    )
    genero = models.CharField('Género',choices=eleccion_de_genero, max_length=10)
    eleccion_del_grupo_sanguineo = (
        ('a+', 'A+'),
        ('o+', 'O+'),
        ('b+', 'B+'),
        ('ab+', 'AB+'),
        ('a-', 'A-'),
        ('o-', 'O-'),
        ('b-', 'B-'),
        ('ab-', 'AB-')
    )
    grupo_sanguineo = models.CharField('Grupo sanguíneo',choices=eleccion_del_grupo_sanguineo, max_length=5)
    e_tin = models.IntegerField(unique=True)
    nid = models.IntegerField(unique=True)
    licencia_manejo_pasaporte = models.IntegerField('licencia de conducir/pasaporte',unique=True)
    numero_teleono = models.CharField('Número de telefono',max_length=11, unique=True)
    email = models.CharField(max_length=255, unique=True)
    nombre_padre = models.CharField('Nombre del Padre',max_length=45)
    nombre_madre = models.CharField('Nombre de la Madre',max_length=45)
    eleccion_de_estado_marital = (
        ('casado', 'Casado'),
        ('viudo', 'viudo'),
        ('separados', 'Separados'),
        ('divorciado', 'Divorciado'),
    )
    estado_marital = models.CharField('Estado Marital',choices=eleccion_de_estado_marital, max_length=10)
    direccion = models.ForeignKey(EmpleadoDireccionInfo, on_delete=models.CASCADE, null=True)
    educacion = models.ForeignKey(EducacionInfo, on_delete=models.CASCADE, null=True)
    capacitacion = models.ForeignKey(EntrenamientoInfo, on_delete=models.CASCADE, null=True)
    trabajo = models.ForeignKey(EmpleadoTrabajoInfo, on_delete=models.CASCADE, null=True)
    experiencia = models.ForeignKey(ExperienciaInfo, on_delete=models.CASCADE, null=True)
    
    def __str__(self):
        return self.nombre

empleado/forms.py
from django import forms
from . import models
from procesos.models import Departmento
class PersonalInfoForm(forms.ModelForm):
    class Meta:
        model = models.PersonalInfo
        exclude = {'direccion', 'educacion', 'capacitacion', 'trabajo', 'experiencia', }
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'foto': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'fecha_nac': forms.DateInput(attrs={'class': 'form-control'}),
            'lugar_nac': forms.TextInput(attrs={'class': 'form-control'}),
            'nacionalidad': forms.Select(attrs={'class': 'form-control'}),
            'religion': forms.Select(attrs={'class': 'form-control'}),
            'genero': forms.Select(attrs={'class': 'form-control'}),
            'grupo_sanguineo': forms.Select(attrs={'class': 'form-control'}),
            'e_tin': forms.NumberInput(attrs={'class': 'form-control'}),
            'nid': forms.NumberInput(attrs={'class': 'form-control'}),
            'licencia_manejo_pasaporte': forms.NumberInput(attrs={'class': 'form-control'}),
            'numero_teleono': forms.NumberInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'nombre_padre': forms.TextInput(attrs={'class': 'form-control'}),
            'nombre_madre': forms.TextInput(attrs={'class': 'form-control'}),
            'estado_marital': forms.Select(attrs={'class': 'form-control'}),

        }

class DireccionInfoForm(forms.ModelForm):
    class Meta:
        model = models.EmpleadoDireccionInfo
        fields = ('zona', 'locacion', 'anexo', 'cp')
        widgets = {
            'zona': forms.Select(attrs={'class': 'form-control'}),
            'locacion': forms.Select(attrs={'class': 'form-control'}),
            'anexo': forms.Select(attrs={'class': 'form-control'}),
            'cp': forms.TextInput(attrs={'class': 'form-control'})
        }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['locacion'].queryset = models.Locacion.objects.none()

            if 'locacion' in self.data:
                try:
                    zona_id = int(self.data.get('zona'))
                    self.fields['locacion'].queryset = models.Locacion.objects.filter(zona_id=zona_id).order_by('nombre')
                except (ValueError, TypeError):
                    pass
            elif self.instance.pk:
                self.fields['locacion'].queryset = self.instance.zona.locacion.order_by('nombre')

            self.fields['anexo'].queryset = models.Anexo.objects.none()

            if 'anexo' in self.data:
                try:
                    locacion_id = int(self.data.get('locacion'))
                    self.fields['anexo'].queryset = models.Anexo.objects.filter(locacion_id=locacion_id).order_by('nombre')
                except (ValueError, TypeError):
                    pass
            elif self.instance.pk:
                self.fields['anexo'].queryset = self.instance.locacion.anexo_set.order_by('nombre')



class EducacionInfoForm(forms.ModelForm):
    class Meta:
        model = models.EducacionInfo
        fields = '__all__'
        widgets = {
            'nombre_de_evaluacion': forms.TextInput(attrs={'class': 'form-control'}),
            'instituto': forms.TextInput(attrs={'class': 'form-control'}),
            'grupo': forms.TextInput(attrs={'class': 'form-control'}),
            'grado': forms.TextInput(attrs={'class': 'form-control'}),
            'reunion': forms.TextInput(attrs={'class': 'form-control'}),
            'anio_presente': forms.NumberInput(attrs={'class': 'form-control'}),
        }

class EntrenamientoInfoForm(forms.ModelForm):
    class Meta:
        model = models.EntrenamientoInfo
        fields = '__all__'
        widgets = {
            'nombre_entrenamiento': forms.TextInput(attrs={'class': 'form-control'}),
            'anio': forms.NumberInput(attrs={'class': 'form-control'}),
            'duracion': forms.NumberInput(attrs={'class': 'form-control'}),
            'lugar': forms.TextInput(attrs={'class': 'form-control'}),
        }

class EmpleadoTrabajoInfoForm(forms.ModelForm):
    class Meta:
        model = models.EmpleadoTrabajoInfo
        fields = '__all__'
        widgets = {
            'categoria': forms.Select(attrs={'class': 'form-control'}),
            'dia_de_ingreso': forms.TextInput(attrs={'class': 'form-control'}),
            'nombre_instituto': forms.TextInput(attrs={'class': 'form-control'}),
            'designacion_de_trabajo': forms.Select(attrs={'class': 'form-control'}),
            'departmento': forms.Select(attrs={'class': 'form-control'}),
            'escala': forms.NumberInput(attrs={'class': 'form-control'}),
            'grado_publicacion': forms.TextInput(attrs={'class': 'form-control'}),
            'primer_periodo_de_contrato': forms.NumberInput(attrs={'class': 'form-control'}),
            'segundo_periodo_de_contrato': forms.NumberInput(attrs={'class': 'form-control'}),
            'promocion_de_vencimiento': forms.NumberInput(attrs={'class': 'form-control'}),
            'renovacion_contrato': forms.NumberInput(attrs={'class': 'form-control'}),
            'tiempo_jubilacion': forms.NumberInput(attrs={'class': 'form-control'}),
        }

class ExperienciaInfoForm(forms.ModelForm):
    class Meta:
        model = models.ExperienciaInfo
        fields = '__all__'
        widgets = {
            'nombre_instituto': forms.TextInput(attrs={'class': 'form-control'}),
            'designation': forms.TextInput(attrs={'class': 'form-control'}),
            'entrenador': forms.TextInput(attrs={'class': 'form-control'}),
        }

empleado/views.py
from django.shortcuts import render,redirect
from . import forms
from .models import Zona,Locacion,Anexo,PersonalInfo
# Create your views here.
def cargar_locacion(request):
    zona_id = request.GET.get('zona')
    locacion = Locacion.objects.filter(zona_id=zona_id).order_by('nombre')

    locacion_id = request.GET.get('locacion')
    anexo = Anexo.objects.filter(locacion_id=locacion_id).order_by('nombre')
    context = {
        'locacion': locacion,
        'anexo': anexo
    }
    return render(request, 'others/locacion_dropdown_list_options.html', context)


def registro_gerente(request):
    form = forms.PersonalInfoForm()
    formulario_direccion = forms.DireccionInfoForm()
    formulario_educacion = forms.EducacionInfoForm()
    formulario_entreamiento = forms.EntrenamientoInfoForm()
    formulario_de_trabajo = forms.EmpleadoTrabajoInfoForm()
    formulario_de_experiencia = forms.ExperienciaInfoForm()
    if request.method == 'POST':
        form = forms.PersonalInfoForm(request.POST, request.FILES)
        formulario_direccion = forms.DireccionInfoForm(request.POST)
        formulario_educacion = forms.EducacionInfoForm(request.POST)
        formulario_entreamiento = forms.EntrenamientoInfoForm(request.POST)
        formulario_de_trabajo = forms.EmpleadoTrabajoInfoForm(request.POST)
        formulario_de_experiencia = forms.ExperienciaInfoForm(request.POST)
        if form.is_valid() and formulario_direccion.is_valid() and formulario_educacion.is_valid() and formulario_entreamiento.is_valid() and formulario_de_trabajo.is_valid() and formulario_de_experiencia.is_valid():
            personal_info = form.save()
            direccion_info = formulario_direccion.save(commit=False)
            direccion_info.direccion = personal_info
            direccion_info.save()
            educacion_info = formulario_educacion.save(commit=False)
            educacion_info.educacion = personal_info
            educacion_info.save()
            entrenamiento_info = formulario_entreamiento.save(commit=False)
            entrenamiento_info.entrenamiento = personal_info
            entrenamiento_info.save()
            trabajo_info = formulario_de_trabajo.save(commit=False)
            trabajo_info.trabajo = personal_info
            trabajo_info.save()
            experiencia_info = formulario_de_experiencia.save(commit=False)
            experiencia_info.experiencia = personal_info
            experiencia_info.save()
            return redirect('empleado-list')

    context = {
        'form': form,
        'formulario_direccion': formulario_direccion,
        'formulario_educacion': formulario_educacion,
        'formulario_entreamiento': formulario_entreamiento,
        'formulario_de_trabajo': formulario_de_trabajo,
        'formulario_de_experiencia': formulario_de_experiencia


    }
    return render(request, 'empleado/empleado-registration.html', context)


def lista_gerente(request):
    gerente = PersonalInfo.objects.all()
    context = {'gerente': gerente}
    return render(request, 'empleado/empleado-list.html', context)

templates/empleado/empleado-list.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
  <div class="animated fadeIn">
      <div class="card">
          <div class="card-header">
              <i class="fa fa-edit"></i> Lista de Empleados
          </div>
          {% if gerente %}
          <div class="card-body">
              <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                  <div class="row">
                      <div class="col-sm-12 col-md-6">
                          <div class="dataTables_length" id="DataTables_Table_0_length">
                              <label>Mostrar
                                  <select name="DataTables_Table_0_length" aria-controls="DataTables_Table_0" class="custom-select custom-select-sm form-control form-control-sm">
                                      <option value="10">10</option>
                                      <option value="25">25</option>
                                      <option value="50">50</option>
                                      <option value="100">100</option>
                                  </select> Entradas</label>
                          </div>
                      </div>
                      <div class="col-sm-12 col-md-6">
                          <div id="DataTables_Table_0_filter" class="dataTables_filter">
                              <label>Buscar:
                                  <input type="search" class="form-control form-control-sm" placeholder="" aria-controls="DataTables_Table_0">
                              </label>
                          </div>
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-sm-12">
                          <table class="table table-striped table-bordered datatable dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info" style="border-collapse: collapse !important">
                              <thead>
                                  <tr role="row">
                                      <th>Id</th>
                                      <th>Nombre</th>
                                      <th>genero</th>
                                      <th>Nacionalidad</th>
                                      <th>Comportamiento</th>
                                  </tr>
                              </thead>
                              <tbody>
                                  {% for gerente in gerente %}
                                    <tr role="row" class="odd">
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ gerente.nombre }}</td>
                                        <td>{{ gerente.genero }}</td>
                                        <td>
                                            <span class="badge badge-warning">{{ gerente.nacionalidad }}</span>
                                        </td>
                                        <td>
                                            <a class="btn btn-success" href="#">
                                                <i class="fa fa-search-plus"></i>
                                            </a>
                                            <a class="btn btn-info" href="#">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                            <a class="btn btn-danger" href="#">
                                                <i class="fa fa-trash-o"></i>
                                            </a>
                                        </td>
                                    </tr>
                                  {% endfor %}
                              </tbody>
                          </table>
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-sm-12 col-md-5">
                          <div class="dataTables_info" id="DataTables_Table_0_info" role="status" aria-live="polite">Mostrando 1 a 10 de 32 entradas</div>
                      </div>
                      <div class="col-sm-12 col-md-7">
                          <div class="dataTables_paginate paging_simple_numbers" id="DataTables_Table_0_paginate">
                              <ul class="pagination">
                                  <li class="paginate_button page-item previous disabled" id="DataTables_Table_0_previous"><a href="#" aria-controls="DataTables_Table_0" data-dt-idx="0" tabindex="0" class="page-link">Previo</a></li>
                                  <li class="paginate_button page-item active"><a href="#" aria-controls="DataTables_Table_0" data-dt-idx="1" tabindex="0" class="page-link">1</a></li>
                                  <li class="paginate_button page-item "><a href="#" aria-controls="DataTables_Table_0" data-dt-idx="2" tabindex="0" class="page-link">2</a></li>
                                  <li class="paginate_button page-item "><a href="#" aria-controls="DataTables_Table_0" data-dt-idx="3" tabindex="0" class="page-link">3</a></li>
                                  <li class="paginate_button page-item "><a href="#" aria-controls="DataTables_Table_0" data-dt-idx="4" tabindex="0" class="page-link">4</a></li>
                                  <li class="paginate_button page-item next" id="DataTables_Table_0_next"><a href="#" aria-controls="DataTables_Table_0" data-dt-idx="5" tabindex="0" class="page-link">Siguiente</a></li>
                              </ul>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          {% endif %}
          <div class="card-body">
              <h3>Ningún empleado encontrado</h3>
          </div>
      </div>
  </div>
{% endblock %}

templates/empleado/empleado-registration.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
  <div class="card">
    <div class="card-header">Formulario de registro de gerentes</div>
    <div class="card-body">
      <form action="" method="post" enctype="multipart/form-data" id="TeacherRegistrationForm" data-locacion-url={% url 'cargar-locacion' %}>

        <div class="card">
          <div class="card-header">Información Personal</div>
          <div class="card-body">
            {% csrf_token %}
            {{ form.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Datos del Domicilio</div>
          <div class="card-body">
            {% csrf_token %}
            {{ formulario_direccion.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Información sobre Educación</div>
          <div class="card-body">
            {% csrf_token %}
            {{ formulario_educacion.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Información de entrenamiento</div>
          <div class="card-body">
            {% csrf_token %}
            {{ formulario_entreamiento.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Informacion del trabajo</div>
          <div class="card-body">
            {% csrf_token %}
            {{ formulario_de_trabajo.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Información de la experiencia</div>
          <div class="card-body">
            {% csrf_token %}
            {{ formulario_de_experiencia.as_p }}
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Enviar</button>
      </form>
      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
      <script>
        $("#id_zona").change(function () {
          var url = $("#TeacherRegistrationForm").attr("data-locacion-url");
          var zonaId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'zona': zonaId
            },
            success: function (data) {
              $("#id_locacion").html(data);
            }
          });

        });
        $("#id_locacion").change(function () {
          var url = $("#TeacherRegistrationForm").attr("data-locacion-url");
          
          var locacionId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'locacion': locacionId
            },
            success: function (data) {
              $("#id_anexo").html(data);
            }
          });

        });
      </script>
    </div>
  </div>
{% endblock %}